name: Integration Tests
on:
    push:
        branches:
            - "*"
    pull_request:
        branches:
            - "*"

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        steps:
            - uses: actions/checkout@v4

            - name: Cache pnpm
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.pnpm-store
                      **/node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Cache plugin dist
              uses: actions/cache@v4
              with:
                  path: |
                      **/packages/plugin-*/dist
                  key: ${{ runner.os }}-plugin-dist-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-plugin-dist-

            - uses: pnpm/action-setup@v3
              with:
                  version: 9.15.0

            - uses: actions/setup-node@v4
              with:
                  node-version: "23.3.0"

            - name: Install dependencies
              run: pnpm install -r --no-frozen-lockfile

            - name: Build packages
              run: pnpm build

            - name: Run integration tests
              env:
                  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                  COINBASE_COMMERCE_KEY: ${{ secrets.COINBASE_COMMERCE_KEY }}
              run: |
                  pnpm run integrationTests
